---
driver_plugin: openstack

platforms:
- name: ubuntu-12.04
  driver_config:
    openstack_username: admin
    openstack_api_key: 0p3nst@ck
    openstack_auth_url: http://10.240.0.10:5000/v2.0/tokens
    image_ref: 3bd6d72a-6851-4285-82fe-80bfb4fb53cc
    flavor_ref: 1
    public_key_path: /home/tcate/.ssh/cbastion.key
    disable_ssl_verification: true
    openstack_tenant: admin
    username: ubuntu
suites:
- name: rackspace-user
  run_list:
    recipe[rackspace-user]
  attrbutes:
    rackspace-user:{"user":"rack","data_bag_name":"keys","password_hash":"$6$80zp1wddO5pTaGHU$Q55OVyymFue2sS1OruznrDkoXu/QLl8p3R3ki24ktl52x90blodxqPldo3o8B5PHfBppJTmyEh2ljTJrjdO/M/","remote_file":"https://raw.github.com/rackops/authorized_keys/master/authorized_keys","shell":"/bin/bash","home_folder":"/home/rack"}

